<?php
use yii\helpers\Html;
use yii\helpers\Url;
$result=Yii::$app->session->getFlash('migrationResult');
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Migrasi & Backup · Catatan Keuangan</title>
<style>
body{font-family:Inter,system-ui,-apple-system,sans-serif;background:#f5f7fb;color:#182230;margin:0}.wrap{max-width:1040px;margin:0 auto;padding:28px 18px 60px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:20px}.card{background:#fff;border:1px solid #e6eaf0;border-radius:18px;padding:20px;margin:14px 0;box-shadow:0 8px 30px rgba(16,24,40,.05)}h1{font-size:28px;margin:0}h2{font-size:18px;margin:0 0 8px}.muted{color:#667085}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:10px;padding:11px 15px;font-weight:700;text-decoration:none;cursor:pointer;background:#175cd3;color:#fff}.btn.secondary{background:#eef4ff;color:#175cd3}.btn.danger{background:#b42318}input[type=file]{width:100%;box-sizing:border-box;padding:12px;border:1px solid #d0d5dd;border-radius:10px;margin:8px 0 12px}.warning{background:#fffaeb;border-color:#fedf89}.ok{background:#ecfdf3;border-color:#abefc6}.info{background:#eff8ff;border-color:#b2ddff}.code{font-family:ui-monospace,monospace;background:#f2f4f7;padding:3px 7px;border-radius:6px;word-break:break-all}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:10px;border-bottom:1px solid #eaecf0;vertical-align:top}.badge{padding:3px 8px;border-radius:999px;background:#f2f4f7}.steps{margin:10px 0 0;padding-left:22px;line-height:1.65}.file-note{font-size:12px;color:#667085;margin:0 0 8px}.selected{padding:9px 11px;border-radius:9px;background:#f2f4f7;font-size:12px;margin:0 0 12px;display:none}
</style></head><body><div class="wrap"><div class="top"><div><h1>Migrasi & Backup MySQL</h1><div class="muted">Super Admin · <?= Html::encode($user['username']??'') ?></div></div><a class="btn secondary" href="<?= Url::to(['site/index']) ?>">← Kembali ke Aplikasi</a></div>

<div class="card info"><h2>Alur Cutover Data Terbaru</h2><ol class="steps"><li>Di <b>aplikasi lama</b>, login sebagai Super Admin lalu buka <b>Admin → Unduh Semua Data</b>.</li><li>Lakukan unduhan sedekat mungkin dengan waktu pemindahan aplikasi agar snapshot berisi transaksi paling baru.</li><li>Di halaman ini pilih file <span class="code">catatan-keuangan-semua-data-YYYYMMDD-HHMMSS.zip</span>.</li><li>Klik <b>Import & Restore Penuh ke MySQL</b>. Setelah berhasil, login kembali menggunakan akun dari aplikasi lama.</li></ol></div>

<?php if($result): ?><div class="card <?= empty($result['warnings'])?'ok':'warning' ?>"><h2>Hasil Restore</h2><pre><?= Html::encode(json_encode($result,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) ?></pre></div><?php endif; ?>

<div class="grid">
<div class="card"><h2>Backup dari Folder Legacy Server</h2><p class="muted">Opsi tambahan jika folder <code>data/</code> aplikasi lama masih tersedia pada server yang sama. Hasilnya menggunakan format ZIP yang sama dengan tombol “Unduh Semua Data” di aplikasi lama.</p><p>Path sumber: <span class="code"><?= Html::encode($legacyPath?:'(belum diatur)') ?></span></p><?php if($legacyPath): ?><form method="post" action="<?= Url::to(['admin/backup-legacy']) ?>"><?= Html::hiddenInput(Yii::$app->request->csrfParam,Yii::$app->request->csrfToken) ?><button class="btn" type="submit">Download Backup JSON Penuh</button></form><?php else: ?><p class="muted">Tidak wajib. Isi <b>LEGACY_DATA_PATH</b> hanya jika Anda ingin membuat backup langsung dari folder server lama.</p><?php endif; ?></div>

<div class="card warning"><h2>Import Backup Terbaru dari Aplikasi Lama</h2><p class="muted">Menerima ZIP dari tombol <b>Unduh Semua Data</b> aplikasi lama. Sistem memvalidasi format, path file, ukuran, dan checksum SHA-256 sebelum database disentuh.</p><p class="file-note">Mode <b>replace_all</b>: data MySQL aplikasi baru akan diganti dengan snapshot dari aplikasi lama, sementara ID lama tetap dipertahankan.</p><form method="post" enctype="multipart/form-data" action="<?= Url::to(['admin/restore']) ?>" onsubmit="return confirm('Restore penuh akan mengganti data MySQL saat ini dengan snapshot aplikasi lama. Pastikan ZIP yang dipilih adalah backup terbaru. Lanjutkan?')"><?= Html::hiddenInput(Yii::$app->request->csrfParam,Yii::$app->request->csrfToken) ?><input id="legacyBackupFile" type="file" name="backup" accept=".zip,application/zip,application/x-zip-compressed" required><div id="legacyBackupSelected" class="selected"></div><button class="btn danger" type="submit">Import & Restore Penuh ke MySQL</button></form></div>
</div>

<?php if($legacyPath): ?><div class="card"><h2>Import Langsung dari Folder Server</h2><p class="muted">Dipakai saat aplikasi lama dan baru berada pada server yang sama. Untuk cutover produksi tetap lebih aman menyimpan ZIP “Unduh Semua Data” sebagai arsip sebelum import.</p><form method="post" action="<?= Url::to(['admin/import-path']) ?>" onsubmit="return confirm('Import langsung akan mengganti data MySQL. Pastikan backup sudah dibuat. Lanjutkan?')"><?= Html::hiddenInput(Yii::$app->request->csrfParam,Yii::$app->request->csrfToken) ?><button class="btn danger">Import dari LEGACY_DATA_PATH</button></form></div><?php endif; ?>

<div class="card"><h2>Riwayat Migrasi</h2><div style="overflow:auto"><table><thead><tr><th>Waktu</th><th>Sumber</th><th>Mode</th><th>Status</th><th>Ringkasan</th></tr></thead><tbody><?php foreach($history as $h): ?><tr><td><?= Html::encode($h['created_at']) ?></td><td><?= Html::encode($h['source_name']) ?></td><td><span class="badge"><?= Html::encode($h['mode']) ?></span></td><td><?= Html::encode($h['status']) ?></td><td><code><?= Html::encode($h['summary_json']??'') ?></code></td></tr><?php endforeach; ?><?php if(!$history): ?><tr><td colspan="5" class="muted">Belum ada migrasi.</td></tr><?php endif; ?></tbody></table></div></div>
</div><script>const f=document.getElementById('legacyBackupFile'),s=document.getElementById('legacyBackupSelected');f?.addEventListener('change',()=>{const x=f.files?.[0];if(!x){s.style.display='none';return;}s.textContent=`Dipilih: ${x.name} · ${(x.size/1024/1024).toFixed(2)} MB`;s.style.display='block';});</script></body></html>
